name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          src: "./src"
          options: "--check"
      - uses: isort/isort-action@master
        with:
          sortPaths: "./src"
          configuration: --check-only --diff --profile=black --skip-gitignore
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: mypy ./src --ignore-missing-imports